site_name: My Blog
theme:
  name: material

nav:
  - Home: index.md
  - Projetos:
     - Zabbix Project: blogs/projetos/zabbixpj.md
  - Estudos:
    - Estudo de Docker: blogs/anotacoes/estudodocker.md